services:
  jaeger:
    image: jaegertracing/jaeger:2.0.0
    container_name: jaeger
    restart: always
    ports:
      - "5778:5778"   # Configuration for clients
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "14250:14250" # gRPC for collectors
      - "14268:14268" # HTTP for collectors
      - "9411:9411"   # Zipkin compatibility
    volumes:
      - "./config-spm.yaml:/etc/jaeger/config.yml"
    command: [ "--config", "/etc/jaeger/config.yml" ]
    networks:
      spring-devops:
        # This is the host name used in Prometheus scrape configuration.
        aliases: [ spm_metrics_source ]

#  microsim:
#    networks:
#      - spring-devops
#    image: yurishkuro/microsim:v0.5.0
#    command: "-d 24h -s 500ms"
#    environment:
#      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jaeger:4318/v1/traces
#    depends_on:
#      - jaeger
  prometheus:
    networks:
      - spring-devops
    image: prom/prometheus:v3.1.0
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
networks:
  spring-devops: