global:
  resolve_timeout: 5m

route:
  receiver: email
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: email
    email_configs:
      - to: "ishimwewil005@gmail.com"
        from: "test@trial-pq3enl65k9r42vwr.mlsender.net"
        smarthost: "smtp.mailersend.net:587"
        auth_username: "MS_darWqk@trial-pq3enl65k9r42vwr.mlsender.net"  # SendGrid requires "apikey" as the username
        auth_password: "mssp.3wUmA79.3yxj6lj6d604do2r.1vgwWoh"  # Replace with your SendGrid API key
        require_tls: true
        send_resolved: true